// Torque Input Map File
if (isObject(moveMap)) moveMap.delete();
new ActionMap(moveMap);
moveMap.bindCmd(keyboard, "escape", "", "handleEscape();");
moveMap.bind(keyboard, "tab", showPlayerList);
moveMap.bind(keyboard, "a", moveleft);
moveMap.bind(keyboard, "d", moveright);
moveMap.bind(keyboard, "left", moveleft);
moveMap.bind(keyboard, "right", moveright);
moveMap.bind(keyboard, "w", moveForward);
moveMap.bind(keyboard, "s", movebackward);
moveMap.bind(keyboard, "up", moveForward);
moveMap.bind(keyboard, "down", movebackward);
moveMap.bind(keyboard, "lcontrol", doCrouch);
moveMap.bind(keyboard, "lshift", doSprint);
moveMap.bindCmd(keyboard, "ctrl k", "commandToServer(\'suicide\');", "");
moveMap.bindCmd(keyboard, "1", "commandToServer(\'use\',\"Ryder\");", "");
moveMap.bindCmd(keyboard, "2", "commandToServer(\'use\',\"Lurker\");", "");
moveMap.bindCmd(keyboard, "3", "commandToServer(\'use\',\"LurkerGrenadeLauncher\");", "");
moveMap.bindCmd(keyboard, "4", "commandToServer(\'use\',\"ProxMine\");", "");
moveMap.bindCmd(keyboard, "5", "commandToServer(\'use\',\"DeployableTurret\");", "");
moveMap.bindCmd(keyboard, "r", "commandToServer(\'reloadWeapon\');", "");
moveMap.bind(keyboard, "0", unmountWeapon);
moveMap.bind(keyboard, "alt w", throwWeapon);
moveMap.bind(keyboard, "alt a", tossAmmo);
moveMap.bind(keyboard, "q", nextWeapon);
moveMap.bind(keyboard, "ctrl q", prevWeapon);
moveMap.bind(keyboard, "t", toggleMessageHud);
moveMap.bind(keyboard, "pageup", pageMessageHudUp);
moveMap.bind(keyboard, "pagedown", pageMessageHudDown);
moveMap.bind(keyboard, "p", resizeMessageHud);
moveMap.bind(keyboard, "f3", startRecordingDemo);
moveMap.bind(keyboard, "f4", stopRecordingDemo);
moveMap.bindCmd(keyboard, "n", "toggleNetGraph();", "");
moveMap.bindCmd(keyboard, "ctrl z", "carjack();", "");
moveMap.bind(keyboard, "f5", doScreenShot);
moveMap.bind(keyboard, "f6", doScreenShotHudless);
moveMap.bind(keyboard, "space", jump);
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(mouse0, "button1", mouseButtonZoom);
moveMap.bind(mouse0, "zaxis", mouseWheelWeaponCycle);
moveMap.bind(gamepad0, "thumbrx", D, "-0.23 0.23", gamepadYaw);
moveMap.bind(gamepad0, "thumbry", D, "-0.23 0.23", gamepadPitch);
moveMap.bind(gamepad0, "thumblx", D, "-0.23 0.23", gamePadMoveX);
moveMap.bind(gamepad0, "thumbly", D, "-0.23 0.23", gamePadMoveY);
moveMap.bindCmd(gamepad0, "btn_back", "disconnect();", "");
moveMap.bindCmd(gamepad0, "lpov", "toggleLightColorViz();", "");
moveMap.bindCmd(gamepad0, "upov", "toggleDepthViz();", "");
moveMap.bindCmd(gamepad0, "dpov", "toggleNormalsViz();", "");
moveMap.bindCmd(gamepad0, "rpov", "toggleLightSpecularViz();", "");
moveMap.bind(gamepad0, "btn_b", doCrouch);
moveMap.bind(gamepad0, "triggerr", gamepadFire);
moveMap.bind(gamepad0, "triggerl", gamepadAltTrigger);
